name: Run pdk test unit

on:
  - pull_request
  - workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Clone repository
      uses: actions/checkout@v4

    - name: Run unit tests
      uses: tom-krieger/action-pdk-test-unit@v6
      with:
        puppet-version: ""
        # [optional]
        # A string indicating the Puppet version to validate against, such as "5.4.2" or "5.5".
        pe-version: ""
        # [optional]
        # A string indicating the PE version to validate against, such as "2017.3.5" or "2018.1".